version: '3.4'

services:
  soap-ws:
    container_name: soap-ws
    hostname: soap-ws
    image: juliocesarmidia/soap-ws:latest
    build:
      context: ./
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 9090:9090
    environment:
      JAVA_OPTIONS: -Xmx400m

networks:
  subnet_0:
    driver: bridge
